/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "mp3.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
		  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 60, 320, 180, 0, 0x0, 0 },
		  { BUTTON_CreateIndirect, "<<<<", ID_BUTTON_0, 27, 102, 80, 45, 0, 0x0, 0 },
		  { BUTTON_CreateIndirect, ">>>>", ID_BUTTON_1, 217, 103, 80, 41, 0, 0x0, 0 },
		  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 32, 69, 263, 20, 0, 0x0, 0 },
		  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 32, 40, 260, 20, 0, 0x0, 0 },
		  { TEXT_CreateIndirect, " MP3 Player", ID_TEXT_1, 32, 10, 259, 20, 0, 0x0, 0 },
		  { BUTTON_CreateIndirect, "play", ID_BUTTON_2, 122, 105, 80, 37, 0, 0x0, 0 },
		  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 171, 165, 119, 32, 0, 0x0, 0 },
		  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 28, 163, 112, 34, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{

	  WM_HWIN hItem;
	  int     NCode;
	  int     Id;
	  // USER START (Optionally insert additional variables)
	  // USER END

	  switch (pMsg->MsgId)
	  {
	  case WM_INIT_DIALOG:
	    //
	    // Initialization of 'Window'
	    //
	    hItem = pMsg->hWin;
	    WINDOW_SetBkColor(hItem, 0x00070707);
	    //
	    // Initialization of 'Text'
	    //
	    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	    TEXT_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
	    TEXT_SetTextColor(hItem, 0x00FFFFFF);
	    //
	    // Initialization of ' MP3 Player'
	    //
	    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	    TEXT_SetFont(hItem, GUI_FONT_COMIC24B_ASCII);
	    TEXT_SetTextColor(hItem, 0x000000FF);
	    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	    // USER START (Optionally insert additional code for further widget initialization)
	    // USER END
	    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
	    SLIDER_SetValue(hItem,0x4a);
	    break;
	  case WM_NOTIFY_PARENT:
	    Id    = WM_GetId(pMsg->hWinSrc);
	    NCode = pMsg->Data.v;
	    switch(Id)
	    {
			case ID_BUTTON_0:
			{
			  switch(NCode)
			  {
			    case WM_NOTIFICATION_CLICKED:

				break;
			  }
			  break;
			}

			case ID_BUTTON_1:
			{
			  switch(NCode)
			  {
			  case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			  }
			  break;
			}

			case ID_BUTTON_2:
			{// Notifications sent by 'play'
			  switch(NCode)
			  {
			  case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			  }
			  break;
			}
			case ID_SLIDER_0:
			{// Notifications sent by 'Slider'
			  switch(NCode)
			  {

			  case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			  // USER START (Optionally insert additional code for further notification handling)
			  // USER END
			  }
			  break;
			}
	    // USER START (Optionally insert additional code for further Ids)
	    // USER END
	    }
	    break;
	  // USER START (Optionally insert additional message handling)
	  // USER END
	  default:
	    WM_DefaultProc(pMsg);
	    break;
	  }
}


/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN CreateWindow(void)
{
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
